# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apka_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from apka_1_single_pushbutton import single_player_pushbutton
from apka_1_multi_pushbutton import multi_player_pushbutton
from apka_1_instruction import connected_with_instruction
from apka_1_text import retranslateUi
from apka_1_title import Wisielec_tittle


class Ui_dialog_game(object):
    def setupUi(self, dialog_game):
        dialog_game.setObjectName("dialog_game")
        dialog_game.resize(677, 574)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            dialog_game.sizePolicy().hasHeightForWidth())
        dialog_game.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        dialog_game.setFont(font)
        dialog_game.setStyleSheet("background-color: #282836;")
        single_player_pushbutton(self, dialog_game)
        multi_player_pushbutton(self, dialog_game)

        Wisielec_tittle(self, dialog_game)
        connected_with_instruction(self, dialog_game)

        QtCore.QMetaObject.connectSlotsByName(dialog_game)

        retranslateUi(self, dialog_game)

    def print_instruction(self):
        self.groupBox_instruction.setVisible(True)

    def hide_instruction(self):
        self.groupBox_instruction.setVisible(False)


if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setStyle("Fusion")
    app = QtWidgets.QApplication(sys.argv)
    dialog_game = QtWidgets.QDialog()
    ui = Ui_dialog_game()
    ui.setupUi(dialog_game)
    dialog_game.show()
    sys.exit(app.exec_())
