from PyQt5 import QtCore


def single_text(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.yes_pushButton.setText(_translate("Dialog", "Tak"))
    self.no_pushButton.setText(_translate("Dialog", "Nie"))
    self.wisielec_label.setText(_translate(
        "Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">WISIELEC</span></p></body></html>"))
    self.a_pushButton.setText(_translate("Dialog", "A"))
    self.aa_pushButton.setText(_translate("Dialog", "Ą"))
    self.b_pushButton.setText(_translate("Dialog", "B"))
    self.c_pushButton.setText(_translate("Dialog", "C"))
    self.cc_pushButton.setText(_translate("Dialog", "Ć"))
    self.nn_pushButton.setText(_translate("Dialog", "Ń"))
    self.o_pushButton.setText(_translate("Dialog", "O"))
    self.d_pushButton.setText(_translate("Dialog", "D"))
    self.n_pushButton.setText(_translate("Dialog", "N"))
    self.m_pushButton.setText(_translate("Dialog", "M"))
    self.e_pushButton.setText(_translate("Dialog", "E"))
    self.ee_pushButton.setText(_translate("Dialog", "Ę"))
    self.oo_pushButton.setText(_translate("Dialog", "Ó"))
    self.p_pushButton.setText(_translate("Dialog", "P"))
    self.r_pushButton.setText(_translate("Dialog", "R"))
    self.q_pushButton.setText(_translate("Dialog", "Q"))
    self.i_pushButton.setText(_translate("Dialog", "I"))
    self.ll_pushButton.setText(_translate("Dialog", "Ł"))
    self.l_pushButton.setText(_translate("Dialog", "L"))
    self.g_pushButton.setText(_translate("Dialog", "G"))
    self.k_pushButton.setText(_translate("Dialog", "K"))
    self.f_pushButton.setText(_translate("Dialog", "F"))
    self.h_pushButton.setText(_translate("Dialog", "H"))
    self.j_pushButton.setText(_translate("Dialog", "J"))
    self.w_pushButton.setText(_translate("Dialog", "W"))
    self.zzz_pushButton.setText(_translate("Dialog", "Ż"))
    self.zz_pushButton.setText(_translate("Dialog", "Ź"))
    self.t_pushButton.setText(_translate("Dialog", "T"))
    self.z_pushButton.setText(_translate("Dialog", "Z"))
    self.s_pushButton.setText(_translate("Dialog", "S"))
    self.u_pushButton.setText(_translate("Dialog", "U"))
    self.y_pushButton.setText(_translate("Dialog", "Y"))
    self.ss_pushButton.setText(_translate("Dialog", "Ś"))
    self.x_pushButton.setText(_translate("Dialog", "X"))
    self.question_label.setText(_translate(
        "Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">Czy chcesz odgadnąć słowo</span></p></body></html>"))
