# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wisielec.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(677, 574)
        Dialog.setStyleSheet("background-color: white")
        self.question_label = QtWidgets.QLabel(Dialog)
        self.question_label.setGeometry(QtCore.QRect(370, 180, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.question_label.setFont(font)
        self.question_label.setStyleSheet("QLabel {\n"
"    color: #565A5B;\n"
"    border: 1px solid black;\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    background-color: #C5DEEB;\n"
"    padding: 3px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #A5E2FF\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0B5AE1;\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #D7B5F9\n"
"        );\n"
"    }")
        self.question_label.setScaledContents(False)
        self.question_label.setWordWrap(False)
        self.question_label.setObjectName("question_label")
        self.yes_pushButton = QtWidgets.QPushButton(Dialog)
        self.yes_pushButton.setGeometry(QtCore.QRect(370, 250, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.yes_pushButton.setFont(font)
        self.yes_pushButton.setStyleSheet("QPushButton {\n"
"    color: #565A5B;\n"
"    border: 1px solid black;\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    background-color: #C5DEEB;\n"
"    padding: 3px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #A5E2FF\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0B5AE1;\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #D7B5F9\n"
"        );\n"
"    }background-color:silver;")
        self.yes_pushButton.setObjectName("yes_pushButton")
        self.no_pushButton = QtWidgets.QPushButton(Dialog)
        self.no_pushButton.setGeometry(QtCore.QRect(510, 250, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.no_pushButton.setFont(font)
        self.no_pushButton.setStyleSheet("QPushButton {\n"
"    color: #565A5B;\n"
"    border: 1px solid black;\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    background-color: #C5DEEB;\n"
"    padding: 3px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #A5E2FF\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    color: #0B5AE1;\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #D7B5F9\n"
"        );\n"
"    }")
        self.no_pushButton.setObjectName("no_pushButton")
        self.wisielec_label = QtWidgets.QLabel(Dialog)
        self.wisielec_label.setGeometry(QtCore.QRect(70, 20, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.wisielec_label.setFont(font)
        self.wisielec_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wisielec_label.setStyleSheet("background-color:transparent;")
        self.wisielec_label.setObjectName("wisielec_label")
        self.a_pushButton = QtWidgets.QPushButton(Dialog)
        self.a_pushButton.setGeometry(QtCore.QRect(90, 450, 21, 28))
        self.a_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.a_pushButton.setObjectName("a_pushButton")
        self.aa_pushButton = QtWidgets.QPushButton(Dialog)
        self.aa_pushButton.setGeometry(QtCore.QRect(120, 450, 21, 28))
        self.aa_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.aa_pushButton.setObjectName("aa_pushButton")
        self.b_pushButton = QtWidgets.QPushButton(Dialog)
        self.b_pushButton.setGeometry(QtCore.QRect(150, 450, 21, 28))
        self.b_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.b_pushButton.setObjectName("b_pushButton")
        self.c_pushButton = QtWidgets.QPushButton(Dialog)
        self.c_pushButton.setGeometry(QtCore.QRect(180, 450, 21, 28))
        self.c_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.c_pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.c_pushButton.setObjectName("c_pushButton")
        self.cc_pushButton = QtWidgets.QPushButton(Dialog)
        self.cc_pushButton.setGeometry(QtCore.QRect(210, 450, 21, 28))
        self.cc_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.cc_pushButton.setObjectName("cc_pushButton")
        self.nn_pushButton = QtWidgets.QPushButton(Dialog)
        self.nn_pushButton.setGeometry(QtCore.QRect(120, 490, 21, 28))
        self.nn_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.nn_pushButton.setObjectName("nn_pushButton")
        self.o_pushButton = QtWidgets.QPushButton(Dialog)
        self.o_pushButton.setGeometry(QtCore.QRect(150, 490, 21, 28))
        self.o_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.o_pushButton.setObjectName("o_pushButton")
        self.d_pushButton = QtWidgets.QPushButton(Dialog)
        self.d_pushButton.setGeometry(QtCore.QRect(240, 450, 21, 28))
        self.d_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.d_pushButton.setObjectName("d_pushButton")
        self.n_pushButton = QtWidgets.QPushButton(Dialog)
        self.n_pushButton.setGeometry(QtCore.QRect(90, 490, 21, 28))
        self.n_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.n_pushButton.setObjectName("n_pushButton")
        self.m_pushButton = QtWidgets.QPushButton(Dialog)
        self.m_pushButton.setGeometry(QtCore.QRect(570, 450, 21, 28))
        self.m_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.m_pushButton.setObjectName("m_pushButton")
        self.e_pushButton = QtWidgets.QPushButton(Dialog)
        self.e_pushButton.setGeometry(QtCore.QRect(270, 450, 21, 28))
        self.e_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.e_pushButton.setObjectName("e_pushButton")
        self.ee_pushButton = QtWidgets.QPushButton(Dialog)
        self.ee_pushButton.setGeometry(QtCore.QRect(300, 450, 21, 28))
        self.ee_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.ee_pushButton.setObjectName("ee_pushButton")
        self.oo_pushButton = QtWidgets.QPushButton(Dialog)
        self.oo_pushButton.setGeometry(QtCore.QRect(180, 490, 21, 28))
        self.oo_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.oo_pushButton.setObjectName("oo_pushButton")
        self.p_pushButton = QtWidgets.QPushButton(Dialog)
        self.p_pushButton.setGeometry(QtCore.QRect(210, 490, 21, 28))
        self.p_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.p_pushButton.setObjectName("p_pushButton")
        self.r_pushButton = QtWidgets.QPushButton(Dialog)
        self.r_pushButton.setGeometry(QtCore.QRect(270, 490, 21, 28))
        self.r_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.r_pushButton.setObjectName("r_pushButton")
        self.q_pushButton = QtWidgets.QPushButton(Dialog)
        self.q_pushButton.setGeometry(QtCore.QRect(240, 490, 21, 28))
        self.q_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.q_pushButton.setObjectName("q_pushButton")
        self.i_pushButton = QtWidgets.QPushButton(Dialog)
        self.i_pushButton.setGeometry(QtCore.QRect(420, 450, 21, 28))
        self.i_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.i_pushButton.setObjectName("i_pushButton")
        self.ll_pushButton = QtWidgets.QPushButton(Dialog)
        self.ll_pushButton.setGeometry(QtCore.QRect(540, 450, 21, 28))
        self.ll_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.ll_pushButton.setObjectName("ll_pushButton")
        self.l_pushButton = QtWidgets.QPushButton(Dialog)
        self.l_pushButton.setGeometry(QtCore.QRect(510, 450, 21, 28))
        self.l_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.l_pushButton.setObjectName("l_pushButton")
        self.g_pushButton = QtWidgets.QPushButton(Dialog)
        self.g_pushButton.setGeometry(QtCore.QRect(360, 450, 21, 28))
        self.g_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.g_pushButton.setObjectName("g_pushButton")
        self.k_pushButton = QtWidgets.QPushButton(Dialog)
        self.k_pushButton.setGeometry(QtCore.QRect(480, 450, 21, 28))
        self.k_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.k_pushButton.setObjectName("k_pushButton")
        self.f_pushButton = QtWidgets.QPushButton(Dialog)
        self.f_pushButton.setGeometry(QtCore.QRect(330, 450, 21, 28))
        self.f_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.f_pushButton.setObjectName("f_pushButton")
        self.h_pushButton = QtWidgets.QPushButton(Dialog)
        self.h_pushButton.setGeometry(QtCore.QRect(390, 450, 21, 28))
        self.h_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.h_pushButton.setObjectName("h_pushButton")
        self.j_pushButton = QtWidgets.QPushButton(Dialog)
        self.j_pushButton.setGeometry(QtCore.QRect(450, 450, 21, 28))
        self.j_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.j_pushButton.setObjectName("j_pushButton")
        self.w_pushButton = QtWidgets.QPushButton(Dialog)
        self.w_pushButton.setGeometry(QtCore.QRect(420, 490, 21, 28))
        self.w_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.w_pushButton.setObjectName("w_pushButton")
        self.zzz_pushButton = QtWidgets.QPushButton(Dialog)
        self.zzz_pushButton.setGeometry(QtCore.QRect(570, 490, 21, 28))
        self.zzz_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.zzz_pushButton.setObjectName("zzz_pushButton")
        self.zz_pushButton = QtWidgets.QPushButton(Dialog)
        self.zz_pushButton.setGeometry(QtCore.QRect(540, 490, 21, 28))
        self.zz_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.zz_pushButton.setObjectName("zz_pushButton")
        self.t_pushButton = QtWidgets.QPushButton(Dialog)
        self.t_pushButton.setGeometry(QtCore.QRect(360, 490, 21, 28))
        self.t_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.t_pushButton.setObjectName("t_pushButton")
        self.z_pushButton = QtWidgets.QPushButton(Dialog)
        self.z_pushButton.setGeometry(QtCore.QRect(510, 490, 21, 28))
        self.z_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.z_pushButton.setObjectName("z_pushButton")
        self.s_pushButton = QtWidgets.QPushButton(Dialog)
        self.s_pushButton.setGeometry(QtCore.QRect(300, 490, 21, 28))
        self.s_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.s_pushButton.setObjectName("s_pushButton")
        self.u_pushButton = QtWidgets.QPushButton(Dialog)
        self.u_pushButton.setGeometry(QtCore.QRect(390, 490, 21, 28))
        self.u_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.u_pushButton.setObjectName("u_pushButton")
        self.y_pushButton = QtWidgets.QPushButton(Dialog)
        self.y_pushButton.setGeometry(QtCore.QRect(480, 490, 21, 28))
        self.y_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.y_pushButton.setObjectName("y_pushButton")
        self.ss_pushButton = QtWidgets.QPushButton(Dialog)
        self.ss_pushButton.setGeometry(QtCore.QRect(330, 490, 21, 28))
        self.ss_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.ss_pushButton.setObjectName("ss_pushButton")
        self.x_pushButton = QtWidgets.QPushButton(Dialog)
        self.x_pushButton.setGeometry(QtCore.QRect(450, 490, 21, 28))
        self.x_pushButton.setStyleSheet("QPushButton {\n"
"                     border-radius: 10px;\n"
"                     background-color: grey;\n"
"                     color: white;\n"
"                     font-size: 16px;\n"
"                     }\n"
"\n"
"QPushButton:hover {\n"
"                    background-color: #C0C0C0;\n"
"                    color: yellow\n"
"                     }\n"
"QPushButton:pressed {\n"
"                     background-color: #A9A9A9;\n"
"                     }")
        self.x_pushButton.setObjectName("x_pushButton")
        self.szub1_label = QtWidgets.QLabel(Dialog)
        self.szub1_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub1_label.setStyleSheet("background-color:transparent;")
        self.szub1_label.setText("")
        self.szub1_label.setPixmap(QtGui.QPixmap("Zdjęcia szubienicy/szub1.png"))
        self.szub1_label.setScaledContents(True)
        self.szub1_label.setObjectName("szub1_label")
        self.szub2_label = QtWidgets.QLabel(Dialog)
        self.szub2_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub2_label.setStyleSheet("background-color:transparent;")
        self.szub2_label.setText("")
        self.szub2_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub2.png.png"))
        self.szub2_label.setObjectName("szub2_label")
        self.szub4_label = QtWidgets.QLabel(Dialog)
        self.szub4_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub4_label.setStyleSheet("background-color:transparent;")
        self.szub4_label.setText("")
        self.szub4_label.setObjectName("szub4_label")
        self.szub3_label = QtWidgets.QLabel(Dialog)
        self.szub3_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub3_label.setStyleSheet("background-color:transparent;")
        self.szub3_label.setText("")
        self.szub3_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub3.png.png"))
        self.szub3_label.setScaledContents(True)
        self.szub3_label.setObjectName("szub3_label")
        self.szub5_label = QtWidgets.QLabel(Dialog)
        self.szub5_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub5_label.setStyleSheet("background-color:transparent;")
        self.szub5_label.setText("")
        self.szub5_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub5.png.png"))
        self.szub5_label.setObjectName("szub5_label")
        self.szub6_label = QtWidgets.QLabel(Dialog)
        self.szub6_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub6_label.setStyleSheet("background-color:transparent;")
        self.szub6_label.setText("")
        self.szub6_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub6.png.png"))
        self.szub6_label.setScaledContents(True)
        self.szub6_label.setObjectName("szub6_label")
        self.szub7_label = QtWidgets.QLabel(Dialog)
        self.szub7_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub7_label.setStyleSheet("background-color:transparent;")
        self.szub7_label.setText("")
        self.szub7_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub7.png.png"))
        self.szub7_label.setObjectName("szub7_label")
        self.szub8_label = QtWidgets.QLabel(Dialog)
        self.szub8_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub8_label.setStyleSheet("background-color:transparent;")
        self.szub8_label.setText("")
        self.szub8_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub8.png.png"))
        self.szub8_label.setObjectName("szub8_label")
        self.szub9_label = QtWidgets.QLabel(Dialog)
        self.szub9_label.setGeometry(QtCore.QRect(0, 70, 381, 500))
        self.szub9_label.setStyleSheet("background-color:transparent;")
        self.szub9_label.setText("")
        self.szub9_label.setPixmap(QtGui.QPixmap("../../../Downloads/szub9.png"))
        self.szub9_label.setObjectName("szub9_label")
        self.finalword_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.finalword_lineEdit.setGeometry(QtCore.QRect(370, 250, 231, 31))
        self.finalword_lineEdit.setStyleSheet("QLineEdit {\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"    padding: 3px;\n"
"    }")
        self.finalword_lineEdit.setObjectName("finalword_lineEdit")
        self.finalword_lineEdit.raise_()
        self.szub2_label.raise_()
        self.szub1_label.raise_()
        self.question_label.raise_()
        self.yes_pushButton.raise_()
        self.no_pushButton.raise_()
        self.wisielec_label.raise_()
        self.a_pushButton.raise_()
        self.aa_pushButton.raise_()
        self.b_pushButton.raise_()
        self.c_pushButton.raise_()
        self.cc_pushButton.raise_()
        self.nn_pushButton.raise_()
        self.o_pushButton.raise_()
        self.d_pushButton.raise_()
        self.n_pushButton.raise_()
        self.m_pushButton.raise_()
        self.e_pushButton.raise_()
        self.ee_pushButton.raise_()
        self.oo_pushButton.raise_()
        self.p_pushButton.raise_()
        self.r_pushButton.raise_()
        self.q_pushButton.raise_()
        self.i_pushButton.raise_()
        self.ll_pushButton.raise_()
        self.l_pushButton.raise_()
        self.g_pushButton.raise_()
        self.k_pushButton.raise_()
        self.f_pushButton.raise_()
        self.h_pushButton.raise_()
        self.j_pushButton.raise_()
        self.w_pushButton.raise_()
        self.zzz_pushButton.raise_()
        self.zz_pushButton.raise_()
        self.t_pushButton.raise_()
        self.z_pushButton.raise_()
        self.s_pushButton.raise_()
        self.u_pushButton.raise_()
        self.y_pushButton.raise_()
        self.ss_pushButton.raise_()
        self.x_pushButton.raise_()
        self.szub4_label.raise_()
        self.szub5_label.raise_()
        self.szub6_label.raise_()
        self.szub7_label.raise_()
        self.szub8_label.raise_()
        self.szub9_label.raise_()
        self.szub3_label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.question_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Czy chcesz odgadnąć hasło?</p></body></html>"))
        self.yes_pushButton.setText(_translate("Dialog", "Tak"))
        self.no_pushButton.setText(_translate("Dialog", "Nie"))
        self.wisielec_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">WISIELEC</span></p></body></html>"))
        self.a_pushButton.setText(_translate("Dialog", "A"))
        self.aa_pushButton.setText(_translate("Dialog", "Ą"))
        self.b_pushButton.setText(_translate("Dialog", "B"))
        self.c_pushButton.setText(_translate("Dialog", "C"))
        self.cc_pushButton.setText(_translate("Dialog", "Ć"))
        self.nn_pushButton.setText(_translate("Dialog", "Ń"))
        self.o_pushButton.setText(_translate("Dialog", "O"))
        self.d_pushButton.setText(_translate("Dialog", "D"))
        self.n_pushButton.setText(_translate("Dialog", "N"))
        self.m_pushButton.setText(_translate("Dialog", "M"))
        self.e_pushButton.setText(_translate("Dialog", "E"))
        self.ee_pushButton.setText(_translate("Dialog", "Ę"))
        self.oo_pushButton.setText(_translate("Dialog", "Ó"))
        self.p_pushButton.setText(_translate("Dialog", "P"))
        self.r_pushButton.setText(_translate("Dialog", "R"))
        self.q_pushButton.setText(_translate("Dialog", "Q"))
        self.i_pushButton.setText(_translate("Dialog", "I"))
        self.ll_pushButton.setText(_translate("Dialog", "Ł"))
        self.l_pushButton.setText(_translate("Dialog", "L"))
        self.g_pushButton.setText(_translate("Dialog", "G"))
        self.k_pushButton.setText(_translate("Dialog", "K"))
        self.f_pushButton.setText(_translate("Dialog", "F"))
        self.h_pushButton.setText(_translate("Dialog", "H"))
        self.j_pushButton.setText(_translate("Dialog", "J"))
        self.w_pushButton.setText(_translate("Dialog", "W"))
        self.zzz_pushButton.setText(_translate("Dialog", "Ż"))
        self.zz_pushButton.setText(_translate("Dialog", "Ź"))
        self.t_pushButton.setText(_translate("Dialog", "T"))
        self.z_pushButton.setText(_translate("Dialog", "Z"))
        self.s_pushButton.setText(_translate("Dialog", "S"))
        self.u_pushButton.setText(_translate("Dialog", "U"))
        self.y_pushButton.setText(_translate("Dialog", "Y"))
        self.ss_pushButton.setText(_translate("Dialog", "Ś"))
        self.x_pushButton.setText(_translate("Dialog", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
